using System;

namespace UberDeployer.WebApp.Core.Services
{
  public class FunnyGifs
  {
    private static readonly Random _rand = new Random();

    private static readonly FunnyGif[] _Gifs =
    {
      new FunnyGif("http://i.imgur.com/BUYqkIj.gif", "Coming to work after having fixed a nighttime outage"),
      new FunnyGif("https://31.media.tumblr.com/c41f651322defdb78ab09b1fd86d310c/tumblr_inline_n0e0qcRAIK1raprkq.gif", "rm -rf filename *"),
      new FunnyGif("https://31.media.tumblr.com/6930c27018b33362d7a93d1b2cf1b772/tumblr_inline_n0e0fwku0g1raprkq.gif", "Explaining how git, gerrit, and jenkins work together"),
      new FunnyGif("http://i.imgur.com/ArblPUI.gif", "Things broke. I'm out."),
      new FunnyGif("http://i.imgur.com/YLS1ufH.gif", "DevOps Reactions for Companies - a free of charge initiative."),
      new FunnyGif("http://i.imgur.com/4xsxFPE.gif", "Looking at someone else's code"),
      new FunnyGif("http://i.imgur.com/3sFfTQL.gif", "Watching the new team deploy to prod"),
      new FunnyGif("http://i.imgur.com/uGHA6u0.gif", "When asked to add a new feature to a 10 years old legacy project"),
      new FunnyGif("https://31.media.tumblr.com/ea36e48e1e7f2f89c974d1ce9bd5179f/tumblr_inline_n0144uUfAx1raprkq.gif", "Exchange Administrator interview"),
      new FunnyGif("http://i.imgur.com/6xGoQrf.gif", "The code refactoring trap"),
      new FunnyGif("https://31.media.tumblr.com/f6d6937584fcfe1a2b47c5a50565c34d/tumblr_inline_mzodr852kj1raprkq.gif", "The unavoidable aftermath of a rushed release"),
      new FunnyGif("https://31.media.tumblr.com/fb43a7440cb68effabc1e94e4a6867d2/tumblr_inline_mzodg3sjJW1raprkq.gif", "Operations and Engineering at full speed"),
      new FunnyGif("https://31.media.tumblr.com/69284aaaf3d86f20cfbbded243b41c4f/tumblr_inline_mzod4o25U31raprkq.gif", "About to put the site live, waiting for the traffic to start"),
      new FunnyGif("http://i.imgur.com/JWETg3r.gif", "Senior in action"),
      new FunnyGif("http://i.imgur.com/IC1V9g4.gif", "Guiding the junior"),
      new FunnyGif("http://i.imgur.com/hdVHGJ8.gif", "After finishing a project"),
      new FunnyGif("https://31.media.tumblr.com/ac02262409dee706640ecfb537eab9f7/tumblr_inline_mzbevzAU0u1raprkq.gif", "Changing permissions that are enforced by cfengine"),
      new FunnyGif("https://31.media.tumblr.com/889c325ffce68b5afebe119c1f53dfee/tumblr_inline_mzberrDG6N1raprkq.gif", "Thinking about next year's targets"),
      new FunnyGif("https://31.media.tumblr.com/189518d0d821918360c03868880a1373/tumblr_inline_mz988fzlQZ1raprkq.jpg", "It's been a year"),
      new FunnyGif("https://i.imgur.com/pKLOPsI.gif", "DoSing ourselves"),
      new FunnyGif("https://i.imgur.com/CGRqaGf.gif", "Penetration testing"),
      new FunnyGif("https://31.media.tumblr.com/a5edfd83a17768f9f9dd4366e34ecad6/tumblr_inline_myycwy2dzv1raprkq.gif", "Realizing I ran the command on the wrong server"),
      new FunnyGif("http://i.imgur.com/HhbogBv.gif", "Fully automated procedures you say?"),
      new FunnyGif("http://i.imgur.com/9VClTYt.gif", "The daily business of QA"),
      new FunnyGif("http://i.imgur.com/UjC1Khr.gif", "Hot-fixing live environment"),
      new FunnyGif("http://i.imgur.com/pOHrSj2.gif", "PM's mentality when telling them there's a 2% chance of success"),
      new FunnyGif("https://31.media.tumblr.com/cf738d014c11b86ea6691a4fe80ae954/tumblr_inline_my8c6pKuIO1raprkq.gif", "for ( ; ; )"),
      new FunnyGif("https://31.media.tumblr.com/f89b0a8102916aea2ea91c6ea8244d0c/tumblr_inline_my8c33PcPA1raprkq.gif", "Senior vs junior sysadmin during an outage"),
      new FunnyGif("https://31.media.tumblr.com/51817fdaff9f36de618208c57d6e2e97/tumblr_inline_my8bz0mEmz1raprkq.gif", "Reading the spec to understand a bug"),
      new FunnyGif("https://31.media.tumblr.com/33032bcbef2c28170beda6d63239e5a7/tumblr_inline_my8brdKuoh1raprkq.gif", "The full picture: A queue of bugs, solving them one by one, sending them to QA, pusing to prod"),
      new FunnyGif("https://31.media.tumblr.com/6d8c32f423550795746deb84bc23b1a3/tumblr_inline_mxzcnayKCb1raprkq.gif", "Going on shift"),
      new FunnyGif("https://31.media.tumblr.com/23ece8f99709ceb0750df7803d7785ad/tumblr_inline_mxzckhZfCw1raprkq.gif", "Our development model"),
      new FunnyGif("http://i.imgur.com/X6WAZc5.gif", "Product manager explains cool new features to developer"),
      new FunnyGif("http://i.imgur.com/xLhL738.gif", "When UK ISP SKY blocked imgur - More info here"),
      new FunnyGif("http://media.tumblr.com/4ef0fd77eee47d384e82372e13520ce1/tumblr_inline_mxinaiXXYk1raprkq.gif", "A moment of self reflection within management after an outage"),
      new FunnyGif("http://i.imgur.com/R9htNz8.gif", "When the specs change"),
      new FunnyGif("http://media.tumblr.com/9d92fdb800f0dafc2f56a11ea8a2ad2e/tumblr_inline_mxio1gmDdB1raprkq.gif", "'Slashdot effect' in your app"),
      new FunnyGif("http://media.tumblr.com/5584bd8c76db38340dce35ec2114850e/tumblr_inline_mxinoj5IC11raprkq.gif", "100 percent uptime for Black Friday and Cyber Monday"),
      new FunnyGif("http://media.tumblr.com/93aa80b795eab73e4691e2320b601436/tumblr_inline_mx5mx8ErBr1raprkq.gif", "When that one cool python feature that you need is only available in python 3"),
      new FunnyGif("http://media.tumblr.com/58d9ab164eb7c0021d3fe3af6194fb15/tumblr_inline_mx5mdoEN4E1raprkq.gif", "Showcasing your cool new feature"),
      new FunnyGif("http://media.tumblr.com/c9108141b14d2d03c003e954731e296e/tumblr_inline_mx5mbkqrQZ1raprkq.gif", "Digging into kernel internals"),
      new FunnyGif("http://i.imgur.com/Ul6Rij3.gif", "Examing the specs"),
      new FunnyGif("http://media.tumblr.com/27d7455f976fa848546cd1b48f02cdc3/tumblr_inline_mwslpu15cj1raprkq.gif", "The moment you realize what exactly you are asked to do"),
      new FunnyGif("http://media.tumblr.com/c10fa9ccf5a19901113b0bd611452604/tumblr_inline_mwslkbsYO71raprkq.gif", "What an admin thinks about a consultant"),
      new FunnyGif("http://i.imgur.com/zCtMzFa.gif", "Successful deployment at last"),
      new FunnyGif("http://media.tumblr.com/efc4b9b73aa9099c490a96857cd5b6f2/tumblr_inline_mwslg2pdjV1raprkq.gif", "Trying to automate things - sometimes"),
      new FunnyGif("http://i.imgur.com/KZPiXO9.gif", "Late for a meeting"),
      new FunnyGif("http://i.imgur.com/7L6nPA4.gif", "Sudden error rate of 50% for your Application"),
      new FunnyGif("http://i.imgur.com/Yh9AQgO.gif", "Why lead"),
      new FunnyGif("http://i.imgur.com/1pkNeOy.gif", "User insists after marking his bug report as WONTFIX"),
      new FunnyGif("http://i.imgur.com/9VM9qDd.gif", "Newly hired sysadmin following SOPs"),
      new FunnyGif("http://i.imgur.com/OQoNOLI.gif", "Port knocking"),
      new FunnyGif("http://i.imgur.com/MdvIXKa.gif", "Why DOS attacks stop - behind the scenes"),
      new FunnyGif("http://media.tumblr.com/8be7468534d182692141c44fdcc708ca/tumblr_inline_mw67p0IfnW1raprkq.gif", "I'll just change this tunable"),
      new FunnyGif("http://i.imgur.com/9g83w6n.gif", "Technical interview of a 20 year old hardcore hacker for a sysadmin role"),
      new FunnyGif("http://i.imgur.com/fyAWEBh.gif", "How it feels when following our policies"),
      new FunnyGif("http://i.imgur.com/vhuRHaW.gif", "That moment..."),
      new FunnyGif("http://media.tumblr.com/b64fc2d58a8f17d25df30ef3d7d5a70d/tumblr_inline_mvrjr0SJD11raprkq.gif", "Looking at what you wrote yesterday"),
      new FunnyGif("http://i.imgur.com/Ycevkxm.gif", "Seeing '* * * * * chmod -R 777 ...' in crontab"),
      new FunnyGif("http://i.imgur.com/wofjBPL.gif", "It's a quick change. clickety click..."),
      new FunnyGif("http://media.tumblr.com/013472172e030bcd2b05c3ecdbed09e9/tumblr_inline_mvqpnm1ebz1raprkq.gif", "Replication out of sync"),
      new FunnyGif("http://media.tumblr.com/ed8cf5db7a9422df5913f9fb1266a80b/tumblr_inline_mvcj2iQdOG1raprkq.gif", "Allowing access to facebook"),
      new FunnyGif("http://i.imgur.com/87KnzSW.gif", "What happens when you don't keep some distance from your customers"),
      new FunnyGif("http://media.tumblr.com/94cc76740add3bb865d6882e48505588/tumblr_inline_mvchdlKDlU1raprkq.gif", "How people feel when CTO enforces dressing code for board meeting"),
      new FunnyGif("http://i.imgur.com/3E0YJ9t.gif", "Realizing that accidentally deleted code was already pushed"),
      new FunnyGif("http://media.tumblr.com/b46dc8e6bc5d50154959f8f71f5e6ff3/tumblr_inline_muzu6hREgn1raprkq.gif", "Tests all green at first run"),
      new FunnyGif("http://media.tumblr.com/7ef0237c00bbd397c5ac392375d212bd/tumblr_inline_muzu5lCkAo1raprkq.gif", "I deleted that line 5 hours ago!"),
      new FunnyGif("http://media.tumblr.com/42fbf2110db79d84ad46a07d8a65b2ab/tumblr_inline_muztxguctE1raprkq.gif", "When it works on a cold clone of prod, but not in prod"),
      new FunnyGif("http://media.tumblr.com/0fb7e245b65446aa3fd3ce26f57a1564/tumblr_inline_mufkhljUKC1raprkq.gif", "Giving an estimate for the next release"),
      new FunnyGif("http://media.tumblr.com/c010bb9c781979aeb66fc9e00c0bbb75/tumblr_inline_mufk7mU38k1raprkq.gif", "service { 'puppet': ensure =&gt; stopped; }"),
      new FunnyGif("http://media.tumblr.com/0981b8439ddf0975130aa194cb13ef4c/tumblr_inline_mufk4aIl4e1raprkq.gif", "Third party webservice went down, took our app with it"),
      new FunnyGif("http://media.tumblr.com/45f0668fbf91495182a19cddd909b375/tumblr_inline_mufju8Xd751raprkq.gif", "11-hour on-call marathon"),
      new FunnyGif("http://i.imgur.com/JLIDTTQ.gif", "Adjusting to minute requirement change"),
      new FunnyGif("http://i.imgur.com/rvIvQPE.gif", "When all the tests pass but deployment fails"),
      new FunnyGif("http://media.tumblr.com/441563bd1b96b2aeecaab1c889f39a78/tumblr_inline_mufg5eAm9Y1raprkq.gif", "Let developers write puppet manifests. Reviewed 2 weeks later."),
      new FunnyGif("http://i.imgur.com/aurlOT9.gif", "Errors in unit-tests and you know it's your fault"),
      new FunnyGif("http://media.tumblr.com/71d9240761e38246a27935334376141c/tumblr_inline_mu9lwrzQhw1raprkq.gif", "Fixing a huge bug with a single line of code"),
      new FunnyGif("http://i.imgur.com/QjpmQPU.gif", "Integrating 3rd party stuff"),
      new FunnyGif("http://media.tumblr.com/42cf1d61acd40b5e167db42bfb8f0608/tumblr_inline_mtuqusUr351raprkq.gif", "Honeypot"),
      new FunnyGif("http://media.tumblr.com/7c9e8bf6ff0775d8372e436cc0a70d62/tumblr_inline_mtuqqojEwx1raprkq.gif", "Our team... some times..."),
      new FunnyGif("http://media.tumblr.com/d93878e7a28174a833b73ef45a34efbf/tumblr_inline_mtuqmqlgiD1raprkq.gif", "Whenever I find an old legacy code bug"),
      new FunnyGif("http://media.tumblr.com/ad0af459b54cb2cb38885d94695d3f18/tumblr_inline_mtuqawVTXO1raprkq.gif", "When the customer wants to add more features before the deadline"),
      new FunnyGif("http://i.imgur.com/J7o5rq5.gif", "When we agree to drop support for an archaic browser"),
      new FunnyGif("http://i.imgur.com/XlRm9Y0.gif", "Keeping our infrastructure running"),
      new FunnyGif("http://media.tumblr.com/f1896cfb88377d6e391ea2ce1bd5cf94/tumblr_inline_mtnewcDiBP1raprkq.gif", "When my coworker complains about how hard to use is Git compared to SVN"),
      new FunnyGif("http://i.imgur.com/ZiIoAUj.gif", "After fixing a difficult bug"),
      new FunnyGif("http://i.imgur.com/0kuLwdM.gif", "Last day before the release"),
      new FunnyGif("http://i.imgur.com/6FOBxrA.gif", "When asked to bugfix legacy perl code"),
      new FunnyGif("http://media.tumblr.com/5488bb525c65730da4c0fb6394cfa53c/tumblr_inline_msu08okvqs1qz4rgp.gif", "Deleting snapshot didn't free as much space as expected"),
      new FunnyGif("http://i.imgur.com/hM9lqGh.gif", "Systems engineering without DevOps tools"),
      new FunnyGif("http://i.imgur.com/zH482fC.gif", "Live demo goes off without a hitch"),
      new FunnyGif("http://i.imgur.com/ePlXDAL.gif", "Waiting for a node to pick up chef settings"),
      new FunnyGif("http://media.tumblr.com/fd60283b88e8ced47b17e4579efc4e24/tumblr_inline_mstzja2bZW1qz4rgp.gif", "Waiting for a multi datacenter puppet run to push a 2 character config change"),
      new FunnyGif("http://media.tumblr.com/951b3aaa905150d18dadc078ee84a5f0/tumblr_inline_mstyimTS5V1qz4rgp.gif", "Some hosting companies on availability"),
      new FunnyGif("http://i.imgur.com/iWRYZI0.gif", "When asked about a 5 year old hack"),
      new FunnyGif("http://i.imgur.com/gbTehJl.gif", "After reading what NSA does to bypass cryptography"),
      new FunnyGif("http://media.tumblr.com/a9fdb12dc6b788db01d682015bb1bc4f/tumblr_inline_mstvb92zoc1qz4rgp.gif", "Ironing out the details"),
      new FunnyGif("http://media.tumblr.com/8c22966dd7590b6878e7e84dc3adaed3/tumblr_inline_msqyz55Pvc1qz4rgp.gif", "After an intense day"),
      new FunnyGif("http://media.tumblr.com/d65bf9cf03b5072cf91a24a9071341b1/tumblr_inline_msqyrw92cc1qz4rgp.gif", "When I go to bed and realize there is still work to do"),
      new FunnyGif("http://media.tumblr.com/8c83c1fe3e4fea864537d7583a746e58/tumblr_inline_msn9ytgWu81qz4rgp.gif", "Trying to get back to sleep after a 3am pagerstorm"),
      new FunnyGif("http://media.tumblr.com/e58f0ce0f18c39950977d1233ffb13b3/tumblr_inline_msb7c8VQhK1qz4rgp.gif", "Reverse Engineering"),
      new FunnyGif("http://media.tumblr.com/0ba3a80e2c73333ebfbb3e4702adf337/tumblr_inline_msb66ljaLn1qz4rgp.gif", "Junior on an interview"),
      new FunnyGif("http://i.imgur.com/GtSUTuh.gif", "Watching Management discuss with Developers"),
      new FunnyGif("http://media.tumblr.com/ae9584a30e65241bedd2b77a3734cb33/tumblr_inline_msb6ldavYC1qz4rgp.gif", "Salesperson enters the NOC"),
      new FunnyGif("http://i.imgur.com/Fy75IvC.gif", "Typical bug fixing"),
      new FunnyGif("http://i.imgur.com/SJxHr.gif", "How managers see themselves when micromanaging"),
      new FunnyGif("http://i.imgur.com/3YXvyRz.gif", "Scoping vs Implementation"),
      new FunnyGif("http://media.tumblr.com/2443321255fd50020eb4d65560991e95/tumblr_inline_mrcees17AF1qz4rgp.gif", "Demoing the product for the first time"),
      new FunnyGif("http://media.tumblr.com/75084c3cbf4cc0712fdf6682323708bd/tumblr_inline_mrced5Bent1qz4rgp.gif", "Staying up late, should be at the office in 4 hours"),
      new FunnyGif("http://i.imgur.com/h8eUL.gif", "Build fails just before creating the executable"),
      new FunnyGif("http://i.imgur.com/hNytIsi.gif", "Development vs Engineering vs Management"),
      new FunnyGif("http://i.imgur.com/D7ymfIc.gif", "When the senior developer tries to teach me how to use his library"),
      new FunnyGif("http://i.imgur.com/Hfnqwi0.gif", "When disaster happens and you don't have DR"),
      new FunnyGif("http://i.imgur.com/dmwyfFi.gif", "Using Linux's bcache+ssd on top of rotational disks"),
      new FunnyGif("http://media.tumblr.com/9a26fb6487c6d2d9a69cabfbc27d0a2c/tumblr_inline_mrccqvkAEy1qz4rgp.gif", "When upper management asks for RCA"),
      new FunnyGif("http://i.imgur.com/IVCI5IU.gif", "Engineering as seen by marketing"),
      new FunnyGif("http://i.imgur.com/29Olztd.gif", "QA gets Hold of the Latest Release"),
      new FunnyGif("http://media.tumblr.com/69e9346eb61c58a4dbe6b45e8ab28e47/tumblr_inline_mrccbaLBCJ1qz4rgp.gif", "Budget when mixing new ideas and consultants"),
      new FunnyGif("http://i.imgur.com/iH5nnIb.gif", "Customer suggesting deployment on a friday"),
      new FunnyGif("http://i.imgur.com/982RQtP.gif", "Oops. Wrong cable."),
      new FunnyGif("http://i.imgur.com/IU8j5nJ.gif", "\"Our engineers are working to fix the problem\". In the meantime behind the scenes"),
      new FunnyGif("http://media.tumblr.com/f3f85f7089e443a5f5f84f321d61d5a1/tumblr_inline_mr6t0irHOj1qz4rgp.gif", "When there is a pagerduty alert and I'm not on call"),
      new FunnyGif("http://media.tumblr.com/df89c2a7db32400003514cc65a1eebe1/tumblr_inline_mr5k8dcJ6d1qz4rgp.gif", "What happens to your carefully developed code when the project reaches the deadline"),
      new FunnyGif("http://i.imgur.com/UNpatrg.gif", "Trying to push a merge conflict fix and receiving a merge conflict"),
      new FunnyGif("http://i.imgur.com/oW9ypTH.gif", "Lead meets devs after refactoring"),
      new FunnyGif("http://i.imgur.com/is8K8zY.gif", "Presenting in a high profile conference"),
      new FunnyGif("http://media.tumblr.com/022622777bfcea698cf86dd18b916802/tumblr_inline_mqingjelky1qz4rgp.gif", "Making a change on prod before testing it on dev"),
      new FunnyGif("http://i.imgur.com/mcESJM2.gif", "Dealing with your 6-months old backlog"),
      new FunnyGif("http://i.imgur.com/u3uRi39.gif", "Teaching SVN users how to GIT"),
      new FunnyGif("http://media.tumblr.com/595baa44767e68669eaaf35aeb507868/tumblr_inline_mqimb9hArg1qz4rgp.gif", "Deep diving into legacy code while hunting a bug"),
      new FunnyGif("http://i.imgur.com/7NglGJX.gif", "This looks secur... wait a minute!"),
      new FunnyGif("http://media.tumblr.com/82715e2d6552ca5b3b2d20cefcdc99cd/tumblr_inline_mqilb78pyf1qz4rgp.gif", "Trying complex code you see on websites"),
      new FunnyGif("http://media.tumblr.com/261eeb21130f6410795e67a00b0455eb/tumblr_inline_mqimcy9hS91qz4rgp.gif", "Pushed sensitive data to Github"),
      new FunnyGif("http://media.tumblr.com/b091731c7b2a18fec75fbb5056a0962b/tumblr_inline_mqi3ryI5HX1qz4rgp.gif", "The boss comes to the office on Monday morning"),
      new FunnyGif("http://media.tumblr.com/aee1876822082583a800f1389c490590/tumblr_inline_mq3vo1vKSL1qz4rgp.gif", "Dealing with new hire's enthusiasm"),
      new FunnyGif("http://i.imgur.com/HMiTx9s.gif", "Plan, deploy aaaand... win!"),
      new FunnyGif("http://i.imgur.com/HpvWY.gif", "Crap, I have no idea which branch I'm working on"),
      new FunnyGif("http://i.imgur.com/Qslh44t.gif", "How our drills look like"),
      new FunnyGif("http://i.imgur.com/vTWrVP0.gif", "Running things because of peer pressure"),
      new FunnyGif("http://media.tumblr.com/21ba9d6af30980fa19b746926d831c36/tumblr_inline_mpum4aF7971qz4rgp.gif", "Getting interrupted while dealing with an outage"),
      new FunnyGif("http://media.tumblr.com/af0fb8666ad1c49db4a778d79e5ad814/tumblr_inline_mpulu1aIaL1qz4rgp.gif", "Concurrently working on a lot of terminals with ssh to multiple hosts"),
      new FunnyGif("http://media.tumblr.com/682e676127eb5dc8a1787262741bc5ad/tumblr_inline_mpulovlWvd1qz4rgp.gif", "Me when asked about next year's plans during the yearly review"),
      new FunnyGif("http://img-fotki.yandex.ru/get/6713/32703389.20/0_6f0a6_b5082f50_orig", "Rollback"),
      new FunnyGif("http://i.imgur.com/JpX3fCQ.jpg", "Spent 4 hours on a bug only to find it was a misspelled variable name"),
      new FunnyGif("http://media.tumblr.com/6975654124d5729b22abb6c97bf3010d/tumblr_inline_mpl4bepowL1qz4rgp.gif", "Paying for SQL Server"),
      new FunnyGif("http://media.tumblr.com/2666f75887c09590958eda247c8f15e8/tumblr_inline_mpl3opPOYZ1qz4rgp.gif", "Fixing bugs"),
      new FunnyGif("http://media.tumblr.com/d7abd17849d02a3c66410fffbe31c8c2/tumblr_inline_moikjsCQWB1qz4rgp.gif", "When someone vilifies opensource"),
      new FunnyGif("http://media.tumblr.com/7aa49ec9751e1d0279866fe09d9a0271/tumblr_inline_moike5aUHa1qz4rgp.gif", "Presenting next year's plans"),
      new FunnyGif("http://i.imgur.com/LI3vaSs.gif", "Protecting your servers during a DDoS"),
      new FunnyGif("http://i.imgur.com/tTzteY6.gif", "Codebase over time"),
      new FunnyGif("http://media.tumblr.com/7c70d884a8ff2e7227fd6cda22ebbb7c/tumblr_inline_moij1tHWwa1qz4rgp.gif", "When you find a stackoverflow question about your problem and there is no response"),
      new FunnyGif("http://media.tumblr.com/420b2da635fefe3717f5df69edf4f3d7/tumblr_inline_moiiyv7qNR1qz4rgp.gif", "Explaining the chain of events that led to the outage"),
      new FunnyGif("http://i.imgur.com/aFsl6z4.gif", "Preventing hacks"),
      new FunnyGif("http://i.imgur.com/71YgV8q.gif", "That was not supposed to work"),
      new FunnyGif("http://i.imgur.com/BEziHmi.gif", "Submitting an idea to the Architect"),
      new FunnyGif("http://i.imgur.com/Z9tbQJF.gif", "Exited editor without saving"),
      new FunnyGif("http://media.tumblr.com/2d901656c495ba7d1292eb980914b0e6/tumblr_inline_moihx0yGsx1qz4rgp.gif", "Stepping a long loop when debugging"),
      new FunnyGif("http://media.tumblr.com/85f122c721f8ec2bc0dbc2bdba521683/tumblr_inline_moihssJm1K1qz4rgp.gif", "When someone converted a python script to a shell script"),
      new FunnyGif("http://media.tumblr.com/eda5c59736d3ec02e3aa91d5f60e2322/tumblr_inline_moihpp5tMR1qz4rgp.gif", "Stress testing"),
      new FunnyGif("http://media.tumblr.com/bd23f816bf3b65eee8573c2ed2ccc249/tumblr_inline_moihlz0EeM1qz4rgp.gif", "Meeting company people on the weekend"),
      new FunnyGif("http://media.tumblr.com/f8c13da3bb264189e9c670c13923ba96/tumblr_inline_moihiys99D1qz4rgp.gif", "When someone creates a pull request without tests"),
      new FunnyGif("http://media.tumblr.com/b7a060895115636de02ca58a0b1a5794/tumblr_inline_moifqlTNfv1qz4rgp.gif", "The effects of tight coupling"),
      new FunnyGif("http://i.imgur.com/ymq7aZ4.gif", "Expecting a DDoS"),
      new FunnyGif("http://media.tumblr.com/6ad6135134ad3fb726b9925e8bc65f3f/tumblr_inline_moie8bICNq1qz4rgp.gif", "Lots of alerts - then realise it's dev environment"),
      new FunnyGif("http://media.tumblr.com/e1797e1ec66b567dc7ee72d620ee6a27/tumblr_inline_mo96s3YJMN1qz4rgp.gif", "Just decreased response time by 100ms"),
      new FunnyGif("http://media.tumblr.com/b5e946fd3c44fb224930594d79dc4e32/tumblr_inline_mo94a32ccO1qz4rgp.gif", "Reaching a dynamic mac learn limit of 8192"),
      new FunnyGif("http://i.imgur.com/x0w5Urk.gif", "Just when you thought you finished working on a project"),
      new FunnyGif("http://i.imgur.com/FFerJOM.gif", "Trying to refactor Perl code"),
      new FunnyGif("http://i.imgur.com/tQLoGU1.gif", "Populating DC cages"),
      new FunnyGif("http://media.tumblr.com/7412fcc1ecca43a174dc11ac0fc2c96e/tumblr_inline_mnotp3FO6U1qz4rgp.gif", "OSPF Split-Brain"),
      new FunnyGif("http://i.imgur.com/8bLC92A.gif", "I don't need this piece of code"),
      new FunnyGif("http://media.tumblr.com/82ac50aa213ee66d3ad028576dee4227/tumblr_inline_mnot73YQjC1qz4rgp.gif", "When you see someone rebasing already pushed changes"),
      new FunnyGif("http://media.tumblr.com/03ed834d8bfcf9f902f1742a0e659c12/tumblr_inline_mncxgo2Qq51qz4rgp.gif", "Convincing the QA that the bug is actually a feature"),
      new FunnyGif("http://i.imgur.com/mMDzLlF.gif", "Final step of our interviews"),
      new FunnyGif("http://i.imgur.com/0RArhfs.gif", "Using unorthodox tricks (a.k.a. hacking)"),
      new FunnyGif("http://i.imgur.com/8MCgAqB.gif", "Troubleshooting a server with bad memory"),
      new FunnyGif("http://i.imgur.com/gy9Kk2l.gif", "Encouraging the usage of coding standards"),
      new FunnyGif("http://i.imgur.com/0U973Je.gif", "Massive puppet deployment going bad unexpectedly"),
      new FunnyGif("http://i.imgur.com/OfyvTuW.gif", "solaris killall"),
      new FunnyGif("http://media.tumblr.com/08b74f6f7242346fea9ca948b0965eca/tumblr_inline_mmrdyb3QSL1qz4rgp.gif", "Escalation procedure"),
      new FunnyGif("http://i.imgur.com/8rMqBIj.gif", "Running gource on a git tree"),
      new FunnyGif("http://i.imgur.com/VQcG7bP.gif", "How an svn user sees git workflow"),
      new FunnyGif("http://media.tumblr.com/7c298196fd347e294a13b3b9d9a91bc8/tumblr_inline_mmrb8pCNj81qz4rgp.gif", "Damn cached JS file"),
      new FunnyGif("http://media.tumblr.com/d2d67bb7def2a454a9246601d34f94e0/tumblr_inline_mmrcbkkYRo1qz4rgp.gif", "When someone mentions he suspects silent disk corruption"),
      new FunnyGif("http://media.tumblr.com/9f73e3f8a958dbe03b0f76f8811a54a1/tumblr_inline_mmrb6wlC0g1qz4rgp.gif", "Hacking"),
      new FunnyGif("http://media.tumblr.com/649308d3719e109a1c87460c652f44c9/tumblr_inline_mmcp5qLjaE1qz4rgp.gif", "Entering a satellite office data cabinet"),
      new FunnyGif("http://media.tumblr.com/526c498002a77f4ab0e127a64081ac12/tumblr_inline_mmcpexRxNJ1qz4rgp.gif", "NSA electronic surveillance"),
      new FunnyGif("http://media.tumblr.com/6c91c8d8471a189e83c41ca869f30c57/tumblr_inline_mmcompbbvP1qz4rgp.gif", "High availability without fencing"),
      new FunnyGif("http://media.tumblr.com/fc4af823163430e45b525ef4a3c5ddd7/tumblr_inline_mmcoea2oQJ1qz4rgp.gif", "Playing with infiniband hardware for the first time"),
      new FunnyGif("http://i.imgur.com/SFiKiLI.gif", "Trying to fix someone else’s CSS"),
      new FunnyGif("http://media.tumblr.com/7e1563ad5f6ebf7c3b6b51150eb03bfb/tumblr_inline_mmawrllsKw1qz4rgp.gif", "Debian Wheezy released"),
      new FunnyGif("http://media.tumblr.com/2b77e868c245f80f4cf19fccb7eca240/tumblr_inline_mlzma3Qe6k1qz4rgp.gif", "Realising the upgrade involves upgrading Ruby"),
      new FunnyGif("http://i.imgur.com/fQhq2.gif", "Testing interface on Internet Explorer"),
      new FunnyGif("http://i.imgur.com/uG9uPDo.gif", "When AWS *might* be having an outage"),
      new FunnyGif("http://i.imgur.com/m7XnClU.gif", "When you see Vagrant"),
      new FunnyGif("http://i.imgur.com/1TLONGY.gif", "Waiting for Pull Request approval"),
      new FunnyGif("http://i.imgur.com/ZDW62tS.gif", "Backup and DR testing"),
      new FunnyGif("http://media.tumblr.com/ad4b6184cd13b9030d26ebec6f9134a9/tumblr_inline_mloizfQcoN1qz4rgp.gif", "Go live day"),
      new FunnyGif("http://media.tumblr.com/97397c17eafcd75b47761144c1b93bbc/tumblr_inline_mloihw93Al1qz4rgp.gif", "When a recruiter sees “DevOps” on your CV"),
      new FunnyGif("http://i.imgur.com/r1cqPE1.gif", "Initial git training"),
      new FunnyGif("http://i.imgur.com/K2aq9.gif", "When caffeine stops working"),
      new FunnyGif("http://i.imgur.com/T5PnOJl.gif", "Unexpected kernel oops while running tail -f /var/log/messages"),
      new FunnyGif("http://i.imgur.com/cOX4HGO.gif", "When You realize You're Using Your Own Library Wrong"),
      new FunnyGif("http://media.tumblr.com/7347acfc654db520a5617d3e4fffd3b9/tumblr_inline_ml4701KEWE1qz4rgp.gif", "Whole suite of automated tests passed"),
      new FunnyGif("http://i.imgur.com/43sf9NL.gif", "I don't need to test that. What can possibly go wrong?"),
      new FunnyGif("http://i.imgur.com/ONuS1Y3.gif", "SysAdmin entering the room"),
      new FunnyGif("http://i.imgur.com/90llhBY.gif", "Ctrl-a d"),
      new FunnyGif("http://i.imgur.com/krhzQKW.gif", "Server response time after Varnish restart"),
      new FunnyGif("http://i.imgur.com/VL5AN4g.gif", "QA's first look at new build"),
      new FunnyGif("http://i.imgur.com/NAqEJfv.gif", "Yahoo VP when told that the private key was bundled with Axis"),
      new FunnyGif("http://i.imgur.com/o1f1YPZ.gif", "Someone enabled DHCP server on their laptop"),
      new FunnyGif("http://i.imgur.com/GyJCAfq.gif", "Blue screen after patching production server"),
      new FunnyGif("http://media.tumblr.com/cfa80ad48d35023420ec652e4e163428/tumblr_inline_ml42hut13M1qz4rgp.gif", "Learning Linux"),
      new FunnyGif("http://media.tumblr.com/f94e761c7584f28fe674582eb812f432/tumblr_inline_ml41kjfXbD1qz4rgp.gif", "When told that the server with 2.5 years uptime was rebooted."),
      new FunnyGif("http://media.tumblr.com/04d329529468cd875def045bbbdfb463/tumblr_inline_mk6xomQvzf1qz4rgp.gif", "Trying to code to W3C standards"),
      new FunnyGif("http://media.tumblr.com/a7854370918696bae609266559e553b4/tumblr_inline_mk6wjt75pb1qz4rgp.gif", "On call, Saturday morning, phone rings, situation critical"),
      new FunnyGif("http://i.imgur.com/CE5uC.gif", "When French homeland intelligence forced wikipedia.fr president to delete an article"),
      new FunnyGif("http://i.imgur.com/u9FX3.gif", "Almost ran UPDATE without WHERE"),
      new FunnyGif("http://media.tumblr.com/44a4f6caf3efff0a92acf7eee3625057/tumblr_inline_mk6w34uaV01qz4rgp.gif", "unpacking .bz2 SQL dump"),
      new FunnyGif("http://img7.joyreactor.cc/pics/post/%D0%B3%D0%B8%D1%84%D0%BA%D0%B8-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D0%BB-%D1%81%D0%B0%D0%BC-599337.gif", "Lead programmer assigns a new task to a developer"),
      new FunnyGif("http://i.imgur.com/j3XBQlC.gif", "Team work"),
      new FunnyGif("http://media.tumblr.com/20b911aae2be3a9172800c518b8a98c0/tumblr_inline_mk6vw92JW51qz4rgp.gif", "The slashdot effect"),
      new FunnyGif("http://i.imgur.com/CHuWU78.gif", "How doing operations feels"),
      new FunnyGif("http://media.tumblr.com/8067e0361e2927be80b8edba089c42f6/tumblr_inline_mk6v8q7iGV1qz4rgp.gif", "When I see a missing semicolon immediately after I committed without testing"),
      new FunnyGif("http://i.imgur.com/spQLb.gif", "Bud during demo - nobody noticed"),
      new FunnyGif("http://i.imgur.com/xgQU30H.gif", "Delivering to management a last-minute request"),
      new FunnyGif("http://media.tumblr.com/01498d16cfca8b7ba123cdb1375e6379/tumblr_inline_mk6u7vJ9Qq1qz4rgp.gif", "The Senior Architect is at the whiteboard"),
      new FunnyGif("http://media.tumblr.com/26e190d919f4c55f1b13a95b7f655fb8/tumblr_inline_mk6veqDS8i1qz4rgp.gif", "After SCRUM morning meeting"),
      new FunnyGif("http://i.imgur.com/XE20szx.gif", "Trying to work out a problem after the 5th hour"),
      new FunnyGif("http://media.tumblr.com/69eb4f42d0a0973c0fa3ae601355f9e4/tumblr_inline_mk6u17ImpK1qz4rgp.gif", "Senior engineer handling the upgrade"),
      new FunnyGif("http://i.imgur.com/FVA4uP2.gif", "Getting rid of old code - Submitted by Stephen"),
      new FunnyGif("http://media.tumblr.com/7b673fb442f6c647b061100fe99e040e/tumblr_inline_mjkn9enrGw1qz4rgp.gif", "Surviving a DDoS attack - Submitted by choult"),
      new FunnyGif("http://i.imgur.com/Gs5BJje.gif", "Oh, we decided that we don't want this - Submitted by Leprosy"),
      new FunnyGif("http://media.tumblr.com/12fbd835b4d508a9217d01a6ba0f217d/tumblr_inline_mjkkcoJW6d1qz4rgp.gif", "Developing without specifications - Submitted by Leprosy"),
      new FunnyGif("http://i.minus.com/iTIoSEWMoiHEZ.gif", "Changing production without backups - Submitted by rockstarcode"),
      new FunnyGif("http://media.tumblr.com/bcca184bac553b2dfade95d3e909b446/tumblr_inline_mjxjq6DHyP1qz4rgp.gif", "When Google added animated image search"),
      new FunnyGif("http://media.tumblr.com/d0e9541d947f824eea7b30fcf977ec8e/tumblr_inline_mjkjs5fiRH1qz4rgp.gif", "Applying rules for PCI compliance"),
      new FunnyGif("http://media.tumblr.com/60a578384a3d0ff3fdcb971f271fae9d/tumblr_inline_mjkje3jJKw1qz4rgp.gif", "When hardware fails you"),
      new FunnyGif("http://media.tumblr.com/60425e6ef4dc35ac83bd3ef23ef3cc8f/tumblr_inline_misumkoT5k1qz4rgp.gif", "3rd failed deployment for today"),
      new FunnyGif("http://i.imgur.com/Nta87n9.gif", "Manual reboot RHEL Cluster Node - Submitted by mrdoro"),
      new FunnyGif("http://i.imgur.com/q7L1gET.gif", "Project managers' logic"),
      new FunnyGif("http://media.tumblr.com/aaa8f51ad3ab21adeb4191659b7248fe/tumblr_inline_misupmB1RC1qz4rgp.gif", "Bug appears during presentation - Submitted by Nacho R"),
      new FunnyGif("http://www.reactiongifs.com/wp-content/uploads/2013/02/nwld.gif", "Last day at work before going on vacation, 5pm - Submitted by Mareshal"),
      new FunnyGif("http://media.tumblr.com/b7eb4f7717579b86547d1949c1fecaf4/tumblr_inline_misu8qRM3G1qz4rgp.gif", "Pushed code to production, recalled there was a critical bug - Submitted by segfault"),
      new FunnyGif("http://media.tumblr.com/b9fc4c4ce9b8e628faeb83e83bec7a97/tumblr_inline_misu5jgtfv1qz4rgp.gif", "When you tell the boss you need one more day for a task - Submitted by Bubu"),
      new FunnyGif("http://i.imgur.com/nlbum.gif", "When your login doesn't work all of a sudden - Submitted by dnol"),
      new FunnyGif("http://i.imgur.com/C0Jc2xd.gif", "Bug reports after a new release - Submitted by Patricio"),
      new FunnyGif("http://media.tumblr.com/a0cac300cf0e64cde94acd7628294ece/tumblr_inline_mj8j8vJNxU1qz4rgp.gif", "First view of a new CSS - ￼ Submitted by Patricio"),
      new FunnyGif("http://media.tumblr.com/050e4da00a1d01ddbeb171d588ae2ab1/tumblr_inline_miss6hkQ6s1qz4rgp.gif", "Checking the logs on a server that's directly accessibly from the Internet - Submitted by vadersfixit"),
      new FunnyGif("http://media.tumblr.com/b4a524bf6c2ee2874566d1d266d88079/tumblr_inline_mj26cs2dtI1qz4rgp.gif", "DevOps Harlem Shake - Submitted by deadpants"),
      new FunnyGif("http://media.tumblr.com/cda999f9eb5857ea62323368f1a94577/tumblr_inline_misrk5wRf81qz4rgp.gif", "Massive git commit has more deletions than insertions - Submitted by Lars"),
      new FunnyGif("http://media.tumblr.com/9a879dcf7a9c47102879ce5be799fd5d/tumblr_inline_misqwmbXAS1qz4rgp.gif", "Indisposable veteran to newbies when an out-of-hours prod change goes bad - Submitted by Scign"),
      new FunnyGif("http://i.imgur.com/1n1A0.gif", "Visiting the guy that wrote the build scripts - Submitted by kosh"),
      new FunnyGif("http://i.imgur.com/kTTGpDd.gif", "Pizza in the noc - Submitted by thebraindeaddj"),
      new FunnyGif("http://i.imgur.com/drIdq.gif", "Starting in a new normal job vs starting as SysAdmin"),
      new FunnyGif("http://i.imgur.com/Jp5fYlk.gif", "Engineering running the production environment - Submitted by Rawb"),
      new FunnyGif("http://media.tumblr.com/e3df0e3c38874ff6c76d3a9a691fa4cb/tumblr_inline_mi4lhudtNe1qz4rgp.gif", "Waiting for cache to clear - Submitted by Fredrik"),
      new FunnyGif("http://media.tumblr.com/590942af6ed06a148c0f0ebb2ca95c2d/tumblr_inline_mi4lg6P2LF1qz4rgp.gif", "Bug goes unnoticed during a presentation - Submitted by Leprosy"),
      new FunnyGif("http://media.tumblr.com/430136cc8f9219b0b9d8c4d3ccbe4dbe/tumblr_inline_mikm4s5zxh1qz4rgp.gif", "When bit.ly flagged devopsreactions tumblr as malicious"),
      new FunnyGif("http://i.imgur.com/GcrIkeh.gif", "Complex regexp worked exactly as expected - Submitted by Leprosy"),
      new FunnyGif("http://i.imgur.com/ldAL5.gif", "The most common incoming request"),
      new FunnyGif("http://media.tumblr.com/0f49ad1b4a039e883e3785c0cde1f4c8/tumblr_inline_mi4kg4bSDR1qz4rgp.gif", "When someone recommends iSCSI - Submitted by Rawb"),
      new FunnyGif("http://i.imgur.com/QcWlT.gif", "How STONITH works"),
      new FunnyGif("http://i.imgur.com/rsiyY.gif", "Coming to work after night deploy went bad - Submitted by admin888"),
      new FunnyGif("http://media.tumblr.com/e1c035e5f102a8ffa7cf8b26355ccc6a/tumblr_inline_mi4jsvEVwg1qz4rgp.gif", "Waiting for a full mysqldump - Submitted by alonp"),
      new FunnyGif("http://i.imgur.com/Xx7FO7Y.gif", "When boss asks for a volunteer to deploy on the weekend - Submitted by Barbarius"),
      new FunnyGif("http://i.imgur.com/Jmee1fw.gif", "When a customer requests a 3AM maintenance window on a Saturday - Submitted by aastaneh"),
      new FunnyGif("http://i.imgur.com/48cuiDd.gif", "Successful production release and let's go for beers - Submitted by sid"),
      new FunnyGif("http://25.media.tumblr.com/tumblr_mdca8l9VJe1qdlh1io1_400.gif", "How I feel trying to restore a server working from my mobile phone - Submitted by eagle1"),
      new FunnyGif("http://media.tumblr.com/0ffb2a3fb20991ea7391e2aed370c036/tumblr_inline_mhetalzhta1qz4rgp.gif", "After a full day of deployment - Submitted by Simon"),
      new FunnyGif("http://media.tumblr.com/80200c3cc786870d0123b131deaac8b2/tumblr_inline_mhetfic6sy1qz4rgp.gif", "Wrote new puppet setup, 200 hundred lines, ran flawlessly first time - Submitted by neverping"),
      new FunnyGif("http://i.imgur.com/qtjtwVA.gif", "Debugging recursive code - Submitted by Petri"),
      new FunnyGif("http://www.ohmagif.com/wp-content/uploads/2013/01/old-man-lighting-a-cigarette-like-a-boss.gif", "Senior Developer explaining how to use his library - Submitted by Rickert"),
      new FunnyGif("http://media.tumblr.com/484df24cc6c79b19b360d53336ac2cd6/tumblr_inline_mhesvgcDpQ1qz4rgp.gif", "Still trying to find the issue after 10 hours"),
      new FunnyGif("http://media.tumblr.com/5e3acd4a03b8fada32e5d58fb08fb5e3/tumblr_inline_mhesmbJRgu1qz4rgp.gif", "Having to work overtime on holidays - Submitted by beasta"),
      new FunnyGif("http://media.tumblr.com/8709facd551bf255501032bfa6bd9faf/tumblr_inline_mhesp3VSVC1qz4rgp.gif", "When an AWS region goes down and you are not using AWS - Submitted by therobot"),
      new FunnyGif("http://media.tumblr.com/f360cf386a93ecc14e0687efd8653716/tumblr_inline_mhes6i4rbc1qz4rgp.gif", "Adding new firewall rules - Submitted by mazvazzeg"),
      new FunnyGif("http://i.imgur.com/msnnn.gif", "Emergency patching at 3am with barely tested code - Submitted by Brian"),
      new FunnyGif("http://media.tumblr.com/c51876c7104492f62b827b1e34f93fab/tumblr_inline_mhagxdlsyz1qz4rgp.gif", "First test - Submitted by ToshkataTonev"),
      new FunnyGif("http://media.tumblr.com/49ff54d3f50e15e5787ddd601fc09b5a/tumblr_inline_mhagp1Kec91qz4rgp.gif", "VP's reaction when woken up because production is FUBARed"),
      new FunnyGif("http://i.imgur.com/sjlsg.gif", "Operations room after a flawless major release (#2)"),
      new FunnyGif("http://weknowmemes.com/wp-content/uploads/2011/11/yea-fuck-yea.gif", "Rebooted a production server and none of the customers noticed... - Submitted by Cyberkef"),
      new FunnyGif("http://i.imgur.com/J47GJ.gif", "When you get the approval to deploy"),
      new FunnyGif("http://media.tumblr.com/tumblr_lw9z84P2pU1qdr5i8.gif", "Customer again reported problem with solution in FAQ - Submitted by Constantine"),
      new FunnyGif("http://25.media.tumblr.com/tumblr_lbdnzkTGkq1qe0eclo1_r1_500.gif", "Asking the security team for a firewall exception - Submitted by Damon"),
      new FunnyGif("http://gifsoup.com/view1/4447907/that-oh-crap-moment-o.gif", "That moment when you realize you've deleted PRODUCTION data... - Submitted by Damon"),
      new FunnyGif("http://i.imgur.com/o0XTn.gif", "Made a production change and didn't tell anyone"),
      new FunnyGif("http://i.imgur.com/0mG9P.gif", "When my boss asks who wants to pick up the weekend shift - Submitted by noname"),
      new FunnyGif("http://i.imgur.com/5KcaY.gif", "Helping another team fix a production issue"),
      new FunnyGif("https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Aaron_Swartz_at_Boston_Wikipedia_Meetup,_2009-08-18_.jpg/300px-Aaron_Swartz_at_Boston_Wikipedia_Meetup,_2009-08-18_.jpg", "A day of silence in memory of Aaron Swartz"),
      new FunnyGif("http://media.tumblr.com/669bf48b0dcd174590f586b5ff02dd79/tumblr_inline_mgj3kioPYQ1raprkq.gif", "Who’s on call during the Christmas party? - Submitted by Juan"),
      new FunnyGif("http://i.imgur.com/59Vt6.gif", "Devs submit code with a smaller version number than is currently in production"),
      new FunnyGif("http://24.media.tumblr.com/tumblr_lryj9sONkA1qjpph7o5_250.gif", "When the boss starts yelling"),
      new FunnyGif("http://media.tumblr.com/tumblr_m8um5czsa51qawgya.gif", "Refactoring the code?"),
      new FunnyGif("http://i.imgur.com/CIGd6.gif", "Someone uses svn blame"),
      new FunnyGif("http://i209.photobucket.com/albums/bb315/DJ_Napps/omg.gif", "When you review undocumented code"),
      new FunnyGif("http://i.imgur.com/HQ07e.gif", "Problem that caused outage is fixed"),
      new FunnyGif("http://i.imgur.com/w3Nbr.gif", "Security hole will not be fixed because Product wants a new feature"),
      new FunnyGif("http://www.ohmagif.com/wp-content/uploads/2012/09/ha-ha-another-white-blonde.gif", "When someone tries to kill a zombie process"),
      new FunnyGif("http://media.tumblr.com/b513e0b60453e7a039a9498766667024/tumblr_inline_mfyydfPkDy1raprkq.gif", "puppet kick going well"),
      new FunnyGif("http://media.tumblr.com/d48f7dc2141d5b7d96fd22f4e84e6565/tumblr_inline_mfyy6gHzRn1raprkq.gif", "When one uses \"ps | grep\" instead of pgrep in scripts"),
      new FunnyGif("http://media.tumblr.com/0cde6afbaa40932ee93df150d9cf24b5/tumblr_inline_mfyxwvB3Hd1raprkq.gif", "Getting locked out"),
      new FunnyGif("http://media.tumblr.com/9cc7aa9d48c9581045f2f12cf6c25715/tumblr_inline_mg2fcsWIoS1raprkq.gif", "Realizing it’s yet another DNS problem - Submitted by Sean"),
      new FunnyGif("http://www.ohmagif.com/wp-content/uploads/2012/11/you-aint-doing-it-right-sir.gif", "kill -9 -1"),
      new FunnyGif("http://i.imgur.com/An059.gif", "An error notification comes in that is related to code you worked on"),
      new FunnyGif("http://media.tumblr.com/b4d3faf444f514b7ec6f876416a9123b/tumblr_inline_mfyw56f40c1raprkq.gif", "Enforcing change windows"),
      new FunnyGif("http://media.tumblr.com/c888a5fc6db74ba2ba4f5dcb3d13e95b/tumblr_inline_mfrh8jAexq1raprkq.gif", "At the office, when there is a change freeze"),
      new FunnyGif("http://media.tumblr.com/8a3680f1239e3759c2ef1162f83a2717/tumblr_inline_mfrh4juPRf1raprkq.gif", "When a person that works for Oracle is spotted in a devops gathering"),
      new FunnyGif("http://www.ohmagif.com/wp-content/uploads/2012/09/flooded-russian-road-win.gif", "Finding the opportunity to test things during an outage"),
      new FunnyGif("http://media.tumblr.com/3f3ad7e26f09c80603123693d82198b9/tumblr_inline_mfrgql4mVv1raprkq.gif", "Carefully examining nagios emails"),
      new FunnyGif("http://media.tumblr.com/1ee23779c54053e5a5045d3a5290af5a/tumblr_inline_mffu42OHMC1raprkq.gif", "Realizing a wrong chown -R"),
      new FunnyGif("http://i.imgur.com/OXuer.gif", "When someone seeks a team member at 5pm"),
      new FunnyGif("http://i.imgur.com/rbVSM.gif", "Using tcpdump"),
      new FunnyGif("http://i.imgur.com/da25D.gif", "Working on the wrong server"),
      new FunnyGif("http://i.imgur.com/oN1Er.gif", "When they tell me that a VP is comming"),
      new FunnyGif("http://i.imgur.com/dImyJ.gif", "When discussing raid and one mentions that more than two disks may fail"),
      new FunnyGif("http://media.tumblr.com/tumblr_mf6wgzJbi51raprkq.gif", "How debugging feels"),
      new FunnyGif("http://media.tumblr.com/tumblr_mf6wbi12ww1raprkq.gif", "My thoughts sometimes"),
      new FunnyGif("http://media.tumblr.com/tumblr_mf6w16Dqav1raprkq.gif", "Suggesting a python book to an empirical learner after looking at his code"),
      new FunnyGif("http://i.imgur.com/SvaAv.gif", "Deciding whether to perform a risky break/fix"),
      new FunnyGif("http://memeorama.com/wp-content/uploads/2012/03/oh-come-on-gif.gif", "Vendor EOL notice contains all of your current hardware - Submitted by @samari711"),
      new FunnyGif("http://i.imgur.com/AgsGW.gif", "After reading the \"Pro Git\" book"),
      new FunnyGif("http://www.ohmagif.com/wp-content/uploads/2012/12/please-wait-i-need-to-play-in-the-puddle.gif", "Finding an interesting side-issue while dealing with something else"),
      new FunnyGif("http://i.imgur.com/MZDDc.gif", "When I realized the leap second problem"),
      new FunnyGif("http://i.imgur.com/c9X6n.gif", "Reaction difference when something breaks and one is on vacation"),
      new FunnyGif("http://i.imgur.com/HhTef.gif", "Review of a sysadmin CV by upper management"),
      new FunnyGif("http://i.imgur.com/YkI29.gif", "How I picture myself at my next job interview"),
      new FunnyGif("http://media.tumblr.com/tumblr_mekca1B9eR1raprkq.gif", "Code review - reviewer"),
      new FunnyGif("http://i.imgur.com/WVsMh.gif", "Code review - reviewee"),
      new FunnyGif("http://media.tumblr.com/tumblr_mekc6kZTap1raprkq.gif", "Typical lunch break"),
      new FunnyGif("http://media.tumblr.com/tumblr_mekc29eIGX1raprkq.gif", "OEL announcements"),
      new FunnyGif("http://i.imgur.com/qBp4u.gif", "When jenkins fails to build the package for the 5th time in a row"),
      new FunnyGif("http://media.tumblr.com/tumblr_mekbxzKXP41raprkq.gif", "Mandatory operations manager study in order to be able to interact with other teams"),
      new FunnyGif("http://media.tumblr.com/tumblr_mekbomumsF1raprkq.gif", "When someone says that he solved the monitoring problem"),
      new FunnyGif("http://media.tumblr.com/tumblr_mekakrsQn61raprkq.gif", "When something breaks just before the lunch break"),
      new FunnyGif("http://media.tumblr.com/tumblr_meja8q02cu1raprkq.gif", "Arguing technical strategies with management"),
      new FunnyGif("http://media.tumblr.com/tumblr_mehas5sRji1raprkq.gif", "One way of doing operations"),
      new FunnyGif("http://i.imgur.com/5sASm.gif", "Our operations team when a customer is visiting the place"),
      new FunnyGif("http://i.imgur.com/f6due.gif", "When someone adopts that solution"),
      new FunnyGif("http://i.imgur.com/O1zDJ.gif", "When someone is going to present a proprietary monolithic monitoring solution"),
      new FunnyGif("http://media.tumblr.com/tumblr_mecsc3c1Mu1raprkq.gif", "When engineering arrives"),
      new FunnyGif("http://media.tumblr.com/tumblr_mecs8veU8n1raprkq.gif", "Going to a conference"),
      new FunnyGif("http://media.tumblr.com/tumblr_mecrrr8ViX1raprkq.gif", "When package promotion gets stuck"),
      new FunnyGif("http://media.tumblr.com/tumblr_mecr1bdMC31raprkq.gif", "Being on-call"),
      new FunnyGif("http://i.imgur.com/JvJRe.gif", "When you thought that you rate limited a customer and you realize that you didn't"),
      new FunnyGif("http://i.imgur.com/bSs6T.gif", "When another opensource project gets acquired"),
      new FunnyGif("http://i.imgur.com/y2Zwk.gif", "The moment you have to pick between puppet and chef"),
      new FunnyGif("http://i.imgur.com/i2Gzs.gif", "When GitHub went down this afternoon"),
      new FunnyGif("http://www.ohmagif.com/wp-content/uploads/2012/11/shocked-at-the-tv-studio.gif", "When someone mentions IPv6"),
      new FunnyGif("http://www.ohmagif.com/wp-content/uploads/2012/05/hulk-smash.gif", "Providing feedback to development"),
      new FunnyGif("http://i.imgur.com/iRXk4.gif", "How people see me when there is an emergency and I'm dealing with it without panicking"),
      new FunnyGif("http://i.imgur.com/1Wz61.gif", "When a server goes down despite our efforts"),
      new FunnyGif("http://gifsoup.com/webroot/animatedgifs4/1163479_o.gif", "Paying a visit to development after spending another whole day dealing with a silly product bug"),
      new FunnyGif("http://i.imgur.com/HzrEB.gif", "When someone asks whether he should use git"),
      new FunnyGif("http://i.imgur.com/Z8P2S.gif", "When you see continuous integration in action"),
      new FunnyGif("http://i.imgur.com/7xpOF.gif", "How time feels when participating in a meeting with non-technical people"),
      new FunnyGif("http://www.ohmagif.com/wp-content/uploads/2012/09/confused-dog-on-escalator.gif", "Troubleshooting the mail queue before finding out that it's a mail loop"),
      new FunnyGif("http://i.imgur.com/P6ToO.gif", "When customer care walks in and asks whether there was any problem with \"the server\" last week"),
      new FunnyGif("http://i.imgur.com/uZnLw.gif", "Breaking production"),
      new FunnyGif("http://i.imgur.com/nJGNY.gif", "Arriving at work when there's a problem"),
      new FunnyGif("http://i.imgur.com/xilCM.gif", "Deploying a change that involves risk to production"),
      new FunnyGif("http://25.media.tumblr.com/tumblr_m8efgpFAgW1qbymseo1_500.gif", "On a call bridge trying to fix a problem"),
      new FunnyGif("http://i.imgur.com/W8myi.jpg", "When working from home and VPN drops for the Nth time killing all ssh sessions"),
      new FunnyGif("http://i.imgur.com/4pGbC.jpg", "Operations vs Engineering"),
    };

    public static FunnyGif GetRandomGif()
    {
      return _Gifs[_rand.Next(0, _Gifs.Length)];
    }
  }
}
